name: Publish Nuget Package

on:
  push:
    tags:
      - "v*.*.*"  # e.g. v1.0.2
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore

      - name: Pack (version from tag)
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          dotnet pack -c Release --no-build -p:PackageVersion=$VERSION -o ./artifacts

      - name: Publish to NuGet.org
        run: |
          dotnet nuget push "./artifacts/*.nupkg" \
            --api-key "${{ secrets.NUGET_API_KEY }}" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate
